### PR TITLE
Expose revision/runtime version

### PR DESCRIPTION
**Pull request by csstaub**
r: @mcpherrinm 
Exposes build revision in `.version` and compiler version in `.compiler`.

### CODE REVIEW

**Comment by mcpherrinm** [comment]
I've been thinking of exposing a few more bits of info, too. Do we want to move these under a folder instead?

**Comment by mcpherrinm** [comment]
:+1: though

**Comment by csstaub** [comment]
Maybe a special `.status` file with a JSON blob and some basic info?

**Comment by mcpherrinm** [comment]
`.json/build` with compiler info, version, compilation date maybe, in a json blob?
I'm fine with whatever, but I don't want to add *too* many dotfiles at the top level.

**Comment by csstaub** [comment]
@mcpherrinm this has been updated, please take a look.

**Comment by mcpherrinm** [comment]
{
  "client_params": {
    "timeout": 2e+10,
    "ca_bundle": "fixtures/cacert.crt",
    "key_file": "fixtures/client.pem",
    "cert_file": "fixtures/client.pem"
  },
  "server_url": {
    "Fragment": "",
    "RawQuery": "",
    "RawPath": "",
    "Path": "",
    "Host": "localhost:4444",
    "User": null,
    "Opaque": "",
    "Scheme": "https"
  },
  "runtime_version": "go1.5.1",
  "start_time": "2016-03-09T20:06:39.955920002Z",
  "build_time": "1970-01-01T00:00:00Z",
  "build_machine": "unknown",
  "build_revision": "unknown"
}

**Comment by mcpherrinm** [comment]
can we get server_url to render as a url, and timeout to not use scientific notation?

**Comment by csstaub** [comment]
@mcpherrinm try again

**Comment by mcpherrinm** [comment]
I added a change to make the ldflag stuff work.

With that, output is:

{"build_revision":"7208d4c09f9777dc23d51798446d489c2ad6cdfb","build_machine":"Linux vm1 2.6.32-504.30.3.el6.x86_64 x86_64","build_time":"2016-03-09T22:35:44Z","start_time":"2016-03-09T22:35:50.74858784Z","
runtime_version":"go1.5.1","server_url":"https://localhost:4444","client_params":{"cert_file":"fixtures/client.pem","key_file":"fixtures/client.pem","ca_bundle":"fixtures/cacert.crt"}}

**Pull request merged**
