### PR TITLE
Show .pprof dir, enable profile debug output

### PR DESCRIPTION
**Pull request by csstaub**
@jbpeirce @worldwise001 @stfinney

### CODE REVIEW

**Comment by csstaub** [comment]
See https://golang.org/pkg/runtime/pprof/#Profile for docs on the profile thing

**Comment by mcpherrinm** [comment]
Does the human readable output still work with "go tool pprof"?

**Comment by csstaub** [comment]
@mcpherrinm afaik yes, but I'll check before I merge.

**Comment by mcpherrinm** [comment]
Cool.  That was the only reason I didn't use human-readable in the first
place - I assumed, perhaps wrongly, the tools didn't want that format.

**Pull request merged**
